### ISSUE TITLE
Does Not Compile with libmicrohttpd version  0.9.71-1

### ISSUE THREAD

**Issue by jenfredwell** [seznam/httpmockserver#5]
```
/src/mock_server.cc: In member function 'void httpmock::MockServer::Server::start(int)':
/src/mock_server.cc:39:17: error: invalid conversion from 'int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**)' {aka 'int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long unsigned int*, void**)'} to 'MHD_AccessHandlerCallback' {aka 'MHD_Result (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long unsigned int*, void**)'} [-fpermissive]
   39 |                 &static_handlerCallback, this, MHD_OPTION_END));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
      |                 |
      |                 int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**) {aka int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long unsigned int*, void**)}
compilation terminated due to -Wfatal-errors.
```

Looks like this is due to a change in libmicrohttpd API 
* https://lists.gnu.org/archive/html/libmicrohttpd/2020-07/msg00011.html
* https://abi-laboratory.pro/index.php?view=changelog&l=libmicrohttpd&v=0.9.71

**Comment by johniez** [comment]
Hi,
you were correct, libmicrohttpd 0.9.71 breaks API compatibility for C++ compilers.
It should be fixed now.
